# Generated by Django 5.2.1 on 2025-05-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
        ('auctions', '0003_add_ticket_purchased_event'),
    ]

    operations = [
    ]
