# Generated by Django 5.2 on 2025-05-15 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.category'),
        ),
        migrations.AddField(
            model_name='lotcategory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.lot'),
        ),
        migrations.AddField(
            model_name='lot',
            name='categories',
            field=models.ManyToManyField(through='lots.LotCategory', to='lots.category'),
        ),
        migrations.AddField(
            model_name='lotimage',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lots.lot'),
        ),
    ]
